[window]
opacity = 0.87

[window.dimensions]
columns = 85
lines = 25

[window.padding]
x = 5
y = 5

[font]
size = 18

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = -5

[colors.primary]
foreground = "#cdc0ad"

[colors.normal]
# black = "#201d1c"
red = "#c65f5f"
green = "#8ca589"
yellow = "#d08b65"
blue = "#728797"
# magenta = "#917b8e"
# cyan = "#829e9b"
# white = "#cdc0ad"

[colors.bright]
# black = "#252221"
red = "#d16a6a"
green = "#95ae92"
yellow = "#d9b27c"
blue = "#7d92a2"
# magenta = "#917b8e"
# cyan = "#749689"
# white = "#cdc0ad"
